.\"Copyright (c) 2024 Christopher Milan <chrismilan@ucla.edu>

.TH PB 1 "23 Oct 2024" "1.0" "pb man page"
.SH NAME
\fBpb\fR \- phonebook information
.SH SYNOPSIS
\fBpb\fR [username]
.SH DESCRIPTION
\fBpb\fR will return neatly formatted phonebook information about a specified
user, or the running user if no user is specified.
.P
\fBpb\fR queries the centralized ldap server for this information, contact your
server administrator to update incorrect information.
.SH AUTHORS
Christopher Milan (chrismilan@ucla.edu)
